[package]
name = "slipstream"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.56", features = ["std", "backtrace"] }
pest = { version = "2.1.3", features = ["pretty-print"] }
pest_derive = "2.1.0"
rustyline = "9.1.2"
