[package]
name = "slipstream"
authors = ["Rafael Bachmann <rafael.bachmann.93@gmail.com>"]
version = "0.1.0"
edition = "2021"

[[bin]]
name = "slipstream"
path = "src/main.rs"

[lib]
name = "slipstream"
path = "src/lib.rs"

[dependencies]
anyhow = { version = "1.0.56", features = ["std", "backtrace"] }
itertools = "0.10.3"
pest = { version = "2.1.3", features = ["pretty-print"] }
pest_derive = "2.1.0"
rustyline = "9.1.2"
